### PR TITLE
Compiled successfully

### PR DESCRIPTION
**Pull request by mostalive**
@adicirstei would you mind if I merge this? Sorry for the old version of firebase used, I've done a migration (with an older version of purescript, as it is part of a product) that I hope to merge after this.

### CODE REVIEW

**Comment by adicirstei** [comment]
no problem. :)

**Comment by MichaelXavier** [comment]
Do it :smile:

**Comment by mostalive** [comment]
:-). Thanks for the encouragement. I will then ;-). Need to do some not-so
nice merging with progress I made in private.

**Comment by mostalive** [comment]
I should have merged this straight away... My apologies. I merged the now newer https://github.com/mostalive/purescript-firebase/pull/8 instead (both of these need the tests upgraded as well, I may do that later).

**Pull request closed without merging**
